### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by kuba-wolf** [JerBouma/FinanceDatabase#7]
After pip installing FinanceDatabase I attempt to import it in my python file, but I get this error: Traceback (most recent call last):
  File "/Users/usrname/PycharmProjects/stockScreener/main.py", line 1, in <module>
    import FinanceDatabase as fd
  File "/Users/usrname/.virtualenvs/stockScreener/lib/python3.8/site-packages/FinanceDatabase/__init__.py", line 2, in <module>
    from .json_picker import select_cryptocurrencies
  File "/Users/usrname/.virtualenvs/stockScreener/lib/python3.8/site-packages/FinanceDatabase/json_picker.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by JerBouma** [comment]
Please check `requirements.txt` for the required packages. You can install requests via `pip install requests`. Same with all other packages listed in the file.
